name: "PHP Lint"

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  tests:
    name: "Lint"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Lint PHP files"
        run: "find src/ tests/ -type f -name '*.php' -print0 | xargs -0 -L1 -P4 -- php -l -f"
