name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.3"
          - "7.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: use https instead of http
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: composer install
        run: composer install --prefer-dist
        env:
          token: ${{secrets.COMPOSER_AUTH}}
      - name: composer test
        run: composer test
